=== 2lambda123/carrot2/etc/component-dependency.dtd
<!-- 
     Component element is the root element of a component
     descriptor file.
     
     It contains component's name (identifier used in other
     descriptors), and an informative description used when printing
     dependencies to an 'info' file.
  -->
<!ELEMENT component (provides*, dependency*) >

<!ATTLIST component name NMTOKEN #REQUIRED >
<!ATTLIST component description CDATA #IMPLIED >

<!-- 
     A dependency to a named component. Only the name of the
     required component is given here - its location is to be
     specified in the build file using nested search paths (filesets).
     
     Dependencies may contain an additional 'profile' attribute.
     A dependency is followed only if the profile specified at
     compilation time is equal to the profile of a dependency, or the
     dependency has no explicit profile.
  -->

<!ELEMENT dependency EMPTY >

<!ATTLIST dependency name NMTOKEN #REQUIRED >
<!ATTLIST dependency profile NMTOKEN #IMPLIED >
<!ATTLIST dependency nocopy (true|false) "false" >
<!ATTLIST dependency in-profile NMTOKEN #IMPLIED >


<!--
    Provides element specifies the objects provided by this component. These
    objects may be either dynamic (created by the component's build file),
    or static (libraries, JARs etc).

    Dynamic objects usually contain 'build' element as a child of
    'provides'. Build element is executed ONLY if some of the objects
    are not found. Whether the state of the objects is up-to-date is
    not detected.

    Static objects only contain 'files' element as a child of 'provides'.
  -->
  
<!ELEMENT provides (files?, build*, check-newer?, meta*) >

<!ATTLIST provides profile NMTOKEN #IMPLIED >

<!-- 
    Files element contains a list of relative paths (resolved
    against the component dependency file) to objects provided
    by the component. Files element may have an optional 'prefix'
    attribute, which specifies path prefix inserted between
    component dependency file and the object's relative path.
    The prefix may be used to ignore path segments leading to 
    a temporary build directory, for example.
  -->
<!ELEMENT files (file+) >
<!ATTLIST files prefix CDATA #IMPLIED >
<!ATTLIST files build-path-exclude (true|false) "false">


<!ELEMENT file EMPTY >
<!ATTLIST file location CDATA #REQUIRED >

<!-- 
    Build element specifies actions that need to be performed
    to create provided objects if they are missing.
  -->
<!ELEMENT build (ant)+ >

<!--
    ANT task is a build action that executes ANT build file
    relative to component descriptor's path/
  -->
<!ELEMENT ant EMPTY >
<!ATTLIST ant file CDATA #REQUIRED >
<!ATTLIST ant target CDATA #IMPLIED >

<!--
    If present, this element will trigger a check if any of the
    provided component's files are older then any of the files
    contained in the given filesets. If so, a rebuild is invoked.
  -->
<!ELEMENT check-newer (fileset+) >

<!--
    An ANT-like fileset. Currently the fileset only supports
    a subset of ANT attributes. The fileset EXCLUDES ANT's default
    excludes from the list.
  -->
<!ELEMENT fileset EMPTY >
<!ATTLIST fileset dir CDATA #REQUIRED >

<!--
    A meta element carries a key and textual content. Metas are used
    to associate extra information with the component, for example
    proguard obfuscation info.
  -->
<!ELEMENT meta (#PCDATA) >
<!ATTLIST meta type CDATA #REQUIRED >

=== 2lambda123/carrot2/carrot2/components/carrot2-input-yahooapi/carrot2-input-yahooapi.dep.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component PUBLIC "-//Carrot2//DTD Component Dependency Descriptor V1.0//EN" "http://www.cs.put.poznan.pl/dweiss/carrot/component-dependency.dtd" >

<component
    name="carrot2-input-yahooapi"
    description="Carrot2 Input Component using YahooAPI">

    <provides profile="local">
        <files build-path-exclude="true" prefix="tmp/dist">
            <file location="carrot2-input-yahooapi.jar" />
        </files>
        <build>
            <ant file="build.local.xml" target="build"/>
        </build>
		<check-newer>
			<fileset dir="src" />
			<fileset dir="web" />
		</check-newer>
    </provides>

    <provides profile="remote">
        <files build-path-exclude="true" prefix="tmp/dist">
            <file location="carrot2-input-yahooapi.war" />
        </files>
        <build>
            <ant file="build.remote.xml" target="build"/>
        </build>
		<check-newer>
			<fileset dir="src" />
			<fileset dir="web" />
		</check-newer>
    </provides>

    <dependency name="log4j" />

    <dependency name="junit" profile="test" />

    <dependency name="carrot2-util-common" />
    <dependency name="carrot2-local-core" />
    <dependency name="carrot2-license" />
    <dependency name="commons-httpclient" />

    <dependency name="servlets-api"           profile="test" />
    <dependency name="carrot2-util-remote"    profile="test" />

    <dependency name="servlets-api"           profile="remote" nocopy="true" />
	<dependency name="carrot2-util-remote" 	  profile="remote" />
</component>

=== 2lambda123/carrot2/components/carrot2-output-xsltrenderer/carrot2-output-xsltrenderer.dep.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../etc/component-dependency.dtd" >

<component
    name="carrot2-output-xsltrenderer"
    description="Carrot2 XSLT Renderer Output Component">

    <provides>
        <files build-path-exclude="true" prefix="tmp/dist">
            <file location="carrot2-output-xsltrenderer.war" />
        </files>
        <build>
            <ant file="build.xml" target="build" />
        </build>
    </provides>

	<!-- Carrot2 components -->
    <dependency name="carrot2-license" />
	<dependency name="carrot2-util-remote" />
	<dependency name="carrot2-util-common" />
	
	<dependency name="saxon" />

</component>

=== 2lambda123/carrot2/carrot2/components/carrot2-util-lang-guesser/carrot2-language-guesser.dep.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../etc/component-dependency.dtd" >

<component
    name="carrot2-language-guesser"
    description="Carrot2 Language Guesser (borrowed from Lucene, Jean-Francois Halleux code)">

    <provides>
        <files build-path-exclude="true" prefix="tmp/dist">
            <file location="carrot2-language-guesser.jar" />
        </files>
        <build>
            <ant file="build.xml" target="build" />
        </build>
    </provides>

    <provides>
        <files>
            <file location="trigrams.LICENSE" />
        </files>
    </provides>

	<!-- Carrot2 components -->
	<dependency name="carrot2-local-core" />
    <dependency name="carrot2-license" />

    <dependency name="junit" profile="test" />

</component>

=== 2lambda123/carrot2/components/carrot2-filter-ahc/carrot2-filter-ahc.dep.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../etc/component-dependency.dtd" >

<component
    name="carrot2-filter-ahc"
    description="Carrot2 AHC Clustering filter">

    <!-- to be written.
    <provides profile="local">
        <files build-path-exclude="true" prefix="tmp/dist">
            <file location="carrot2-filter-ahc-local.jar" />
        </files>
        <build>
            <ant file="build.local.xml" target="build" />
        </build>
    </provides>
    -->

    <provides profile="remote">
        <files build-path-exclude="true" prefix="tmp/dist">
            <file location="carrot2-filter-ahc.war" />
        </files>
        <build>
            <ant file="build.remote.xml" target="build" />
        </build>
    </provides>

	<!-- Carrot2 components -->
    <dependency name="carrot2-license" />
	<dependency name="carrot2-util-common"  />

	<dependency name="carrot2-util-remote" 	profile="remote" />

</component>

=== 2lambda123/carrot2/carrot2/components/carrot2-input-tree-snippet-miner/carrot2-input-tree-snippet-miner.dep.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../etc/component-dependency.dtd" >

<component
    name="carrot2-input-tree-snippet-miner"
    description="Carrot2 Tree Snippet Miner Input Component">

    <provides>
        <files build-path-exclude="true" prefix="tmp/dist">
            <file location="carrot2-input-tree-snippet-miner.war" />
        </files>
        <build>
            <ant file="build.xml" target="build" />
        </build>
    </provides>

	<!-- Carrot2 components -->
    <dependency name="carrot2-license" />
	<dependency name="carrot2-util-remote" />
	<dependency name="carrot2-util-common" />
	<dependency name="carrot2-util-put" />
	<dependency name="log4j" />
	<dependency name="jdom" />
	<dependency name="gnu-regexp" />

</component>

=== 2lambda123/carrot2/components/carrot2-local-core/carrot2-local-core.dep.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component PUBLIC "-//Carrot2//DTD Component Dependency Descriptor V1.0//EN"
	"http://www.carrot2.org/dtd/component-dependency.dtd" >

<component
    name="carrot2-local-core"
    description="Carrot2 Core (Local Interfaces)">
    
    <provides>
        <files build-path-exclude="true" prefix="tmp/dist">
            <file location="carrot2-local-core.jar" />
        </files>
        <build>
            <ant file="build.xml" target="build"/>
        </build>
		<check-newer>
			<fileset dir="src" />
		</check-newer>
    </provides>

    <dependency name="log4j" />
    <dependency name="dom4j" />
    <dependency name="commons-pool" />
    <dependency name="carrot2-license" />
    <dependency name="carrot2-util-common" />
</component>

=== 2lambda123/carrot2/components/carrot2-ant-extensions/dtd/component-dependency-example.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "component-dependency.dtd" >

<component name="myComponent" description="This is myComponent, see http://www.mycomponent.org">

	<provides>
		<files prefix="tmp/dist">
			<file location="a-out.txt" />
		</files>
		<build>
			<ant file="build.xml" target="build" />
		</build>
	</provides>

    <dependency name="b" />
	<dependency name="c" profile="test" />
</component>

=== 2lambda123/carrot2/components/carrot2-filter-stemmer/carrot2-filter-stemmer.dep.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE component SYSTEM "../../etc/component-dependency.dtd" >

<component
    name="carrot2-filter-stemmer"
    description="Carrot2 Stemming Component (for remote components architecture)">

    <provides>
        <files build-path-exclude="true" prefix="tmp/dist">
            <file location="carrot2-filter-stemmer.war" />
        </files>
        <build>
            <ant file="build.xml" target="build" />
        </build>
    </provides>

	<!-- Carrot2 components -->
    <dependency name="carrot2-license" />
	<dependency name="carrot2-util-common" />
	<dependency name="carrot2-util-remote" />

	<dependency name="carrot2-util-tokenizer" />
	<dependency name="carrot2-language-guesser" />
	<dependency name="carrot2-local-core" />

	<dependency name="jdom" />

</component>
